// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCS.Services;

#nullable disable

namespace SCS.Migrations
{
    [DbContext(typeof(Service))]
    partial class ServiceModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SCS.Models.Almacenamiento", b =>
                {
                    b.Property<int>("Id_almacenamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_almacenamiento"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Archivo")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Cantidad_Disponible")
                        .HasColumnType("int");

                    b.Property<string>("Colateral")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fecha_Ingreso")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_Vencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_parte")
                        .HasColumnType("int");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Numero_parte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Part")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Parte");

                    b.Property<string>("Suplidor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_almacenamiento");

                    b.ToTable("Almacenamientos");
                });

            modelBuilder.Entity("SCS.Models.BitacoraEntradasSalidas", b =>
                {
                    b.Property<int>("Id_ent_sal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_ent_sal"));

                    b.Property<int?>("EgresosId_transaccion_eg")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha_entrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_salida")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("Hora_entrada")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("Hora_salida")
                        .HasColumnType("time");

                    b.Property<int?>("Id_perfil")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("IngresosId_transaccion_ing")
                        .HasColumnType("int");

                    b.Property<string>("Tipo_movimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_ent_sal");

                    b.HasIndex("EgresosId_transaccion_eg");

                    b.HasIndex("Id_perfil");

                    b.HasIndex("IngresosId_transaccion_ing");

                    b.ToTable("Entradas_Salidas");
                });

            modelBuilder.Entity("SCS.Models.BitacoraMovimientos", b =>
                {
                    b.Property<int>("Id_movimientos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_movimientos"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EgresosId_transaccion_eg")
                        .HasColumnType("int");

                    b.Property<int?>("EntradasSalidasId_ent_sal")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha_accion")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("Hora_accion")
                        .HasColumnType("time");

                    b.Property<int?>("Id_perfi")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("IngresosId_transaccion_ing")
                        .HasColumnType("int");

                    b.Property<int?>("ParteId_parte")
                        .HasColumnType("int");

                    b.Property<int?>("RolId_roles")
                        .HasColumnType("int");

                    b.Property<int?>("SuplidorId_suplidor")
                        .HasColumnType("int");

                    b.Property<string>("Tipo_accion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_movimientos");

                    b.HasIndex("EgresosId_transaccion_eg");

                    b.HasIndex("EntradasSalidasId_ent_sal");

                    b.HasIndex("Id_perfi");

                    b.HasIndex("IngresosId_transaccion_ing");

                    b.HasIndex("ParteId_parte");

                    b.HasIndex("RolId_roles");

                    b.HasIndex("SuplidorId_suplidor");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("SCS.Models.Egresos", b =>
                {
                    b.Property<int>("Id_transaccion_eg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_transaccion_eg"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fecha_salida")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_parte")
                        .HasColumnType("int");

                    b.Property<int>("Id_perfil")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Numero_serial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario_salida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuariosId_perfiles")
                        .HasColumnType("int");

                    b.HasKey("Id_transaccion_eg");

                    b.HasIndex("Id_parte");

                    b.HasIndex("UsuariosId_perfiles");

                    b.ToTable("Egresos");
                });

            modelBuilder.Entity("SCS.Models.Fabricantes", b =>
                {
                    b.Property<int>("Id_suplidor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_suplidor"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Colateral")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Condiciones")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("Fecha_Registro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre_Suplidor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_suplidor");

                    b.ToTable("Fabricantes");
                });

            modelBuilder.Entity("SCS.Models.Ingresos", b =>
                {
                    b.Property<int>("Id_transaccion_ing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_transaccion_ing"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fecha_ingreso")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_parte")
                        .HasColumnType("int");

                    b.Property<int>("Id_perfil")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Numero_serial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario_ingreso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuariosId_perfiles")
                        .HasColumnType("int");

                    b.HasKey("Id_transaccion_ing");

                    b.HasIndex("Id_parte");

                    b.HasIndex("UsuariosId_perfiles");

                    b.ToTable("Ingresos");
                });

            modelBuilder.Entity("SCS.Models.Objetos", b =>
                {
                    b.Property<int>("Id_parte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_parte"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Archivo")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Cantidad_Disponible")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Ingreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_Vencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero_parte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock_Maximo")
                        .HasColumnType("int");

                    b.Property<int>("Stock_Minimo")
                        .HasColumnType("int");

                    b.Property<int>("SuplidorId")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuariosId_perfiles")
                        .HasColumnType("int");

                    b.HasKey("Id_parte");

                    b.HasIndex("SuplidorId");

                    b.HasIndex("UsuariosId_perfiles");

                    b.ToTable("Objetos");
                });

            modelBuilder.Entity("SCS.Models.Permisos", b =>
                {
                    b.Property<int>("Id_permiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_permiso"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("NombrePermiso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_permiso");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("SCS.Models.Roles", b =>
                {
                    b.Property<int>("Id_roles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_roles"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_roles");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SCS.Models.RolesPermisos", b =>
                {
                    b.Property<int>("Id_role_permiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_role_permiso"));

                    b.Property<int>("PermisoId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id_role_permiso");

                    b.HasIndex("PermisoId");

                    b.HasIndex("RolId");

                    b.ToTable("RolePermisos");
                });

            modelBuilder.Entity("SCS.Models.Usuarios", b =>
                {
                    b.Property<int>("Id_perfiles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_perfiles"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Confirmacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Id_rol")
                        .HasColumnType("int");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RolesId_roles")
                        .HasColumnType("int");

                    b.Property<string>("Superior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WWID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_perfiles");

                    b.HasIndex("Id_rol");

                    b.HasIndex("RolesId_roles");

                    b.ToTable("Perfiles");
                });

            modelBuilder.Entity("SCS.ViewModels.UsuarioRole", b =>
                {
                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("RolId")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("SCS.Models.BitacoraEntradasSalidas", b =>
                {
                    b.HasOne("SCS.Models.Egresos", "Egresos")
                        .WithMany()
                        .HasForeignKey("EgresosId_transaccion_eg");

                    b.HasOne("SCS.Models.Usuarios", "Perfil")
                        .WithMany("EntradasSalidas")
                        .HasForeignKey("Id_perfil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SCS.Models.Ingresos", "Ingresos")
                        .WithMany()
                        .HasForeignKey("IngresosId_transaccion_ing");

                    b.Navigation("Egresos");

                    b.Navigation("Ingresos");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("SCS.Models.BitacoraMovimientos", b =>
                {
                    b.HasOne("SCS.Models.Egresos", "Egresos")
                        .WithMany()
                        .HasForeignKey("EgresosId_transaccion_eg")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SCS.Models.BitacoraEntradasSalidas", "EntradasSalidas")
                        .WithMany()
                        .HasForeignKey("EntradasSalidasId_ent_sal");

                    b.HasOne("SCS.Models.Usuarios", "Perfil")
                        .WithMany("Movimientos")
                        .HasForeignKey("Id_perfi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SCS.Models.Ingresos", "Ingresos")
                        .WithMany()
                        .HasForeignKey("IngresosId_transaccion_ing")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SCS.Models.Objetos", "Parte")
                        .WithMany()
                        .HasForeignKey("ParteId_parte")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SCS.Models.Roles", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId_roles");

                    b.HasOne("SCS.Models.Fabricantes", "Suplidor")
                        .WithMany()
                        .HasForeignKey("SuplidorId_suplidor");

                    b.Navigation("Egresos");

                    b.Navigation("EntradasSalidas");

                    b.Navigation("Ingresos");

                    b.Navigation("Parte");

                    b.Navigation("Perfil");

                    b.Navigation("Rol");

                    b.Navigation("Suplidor");
                });

            modelBuilder.Entity("SCS.Models.Egresos", b =>
                {
                    b.HasOne("SCS.Models.Objetos", "Parte")
                        .WithMany("Egresos")
                        .HasForeignKey("Id_parte")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SCS.Models.Usuarios", null)
                        .WithMany("Egreso")
                        .HasForeignKey("UsuariosId_perfiles");

                    b.Navigation("Parte");
                });

            modelBuilder.Entity("SCS.Models.Ingresos", b =>
                {
                    b.HasOne("SCS.Models.Objetos", "Parte")
                        .WithMany("Ingresos")
                        .HasForeignKey("Id_parte")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SCS.Models.Usuarios", null)
                        .WithMany("Ingreso")
                        .HasForeignKey("UsuariosId_perfiles");

                    b.Navigation("Parte");
                });

            modelBuilder.Entity("SCS.Models.Objetos", b =>
                {
                    b.HasOne("SCS.Models.Fabricantes", "Suplidor")
                        .WithMany("Partes")
                        .HasForeignKey("SuplidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SCS.Models.Usuarios", null)
                        .WithMany("Partes")
                        .HasForeignKey("UsuariosId_perfiles");

                    b.Navigation("Suplidor");
                });

            modelBuilder.Entity("SCS.Models.RolesPermisos", b =>
                {
                    b.HasOne("SCS.Models.Permisos", "Permiso")
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SCS.Models.Roles", "Rol")
                        .WithMany("RolePermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SCS.Models.Usuarios", b =>
                {
                    b.HasOne("SCS.Models.Roles", "Rol")
                        .WithMany()
                        .HasForeignKey("Id_rol")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SCS.Models.Roles", null)
                        .WithMany("Perfiles")
                        .HasForeignKey("RolesId_roles");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SCS.ViewModels.UsuarioRole", b =>
                {
                    b.HasOne("SCS.Models.Roles", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SCS.Models.Usuarios", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SCS.Models.Fabricantes", b =>
                {
                    b.Navigation("Partes");
                });

            modelBuilder.Entity("SCS.Models.Objetos", b =>
                {
                    b.Navigation("Egresos");

                    b.Navigation("Ingresos");
                });

            modelBuilder.Entity("SCS.Models.Roles", b =>
                {
                    b.Navigation("Perfiles");

                    b.Navigation("RolePermisos");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("SCS.Models.Usuarios", b =>
                {
                    b.Navigation("Egreso");

                    b.Navigation("EntradasSalidas");

                    b.Navigation("Ingreso");

                    b.Navigation("Movimientos");

                    b.Navigation("Partes");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
